### ISSUE TITLE
Compiling on OSX

### ISSUE THREAD

**Issue by carlskii** [cisco/libest#22]
Hi I just followed the instructions in the README but I'm getting a file not found issue. 

```
In file included from est.c:22:
./est.h:17:10: fatal error: 'openssl/srp.h' file not found
#include <openssl/srp.h>
```

**Comment by jfigus** [comment]
I've never tried to compile on OSX.  It should work using an appropriate compiler such as gcc or clang.  But does OSX support autoconf?  Based on the error message you provided it appears the OpenSSL header files are not installed or can't be found on the system.  Also, which README are you referring too?  I don't see OSX build instructions in the top level README.

**Comment by carlskii** [comment]
OK thanks. I built an Ubuntu VM and everything works OK.
