### ISSUE TITLE
testrfc7030.cisco.com vs example/server

### ISSUE THREAD

**Issue by tysonite** [cisco/libest#37]
Hello!

I would like to understand difference (both comparing to spec. and in terms of configuration) between EST server running on testrfc7030.cisco.com and an example of EST server located in example/server directory.

I see from my tests that at least enabled ciphers are different. Please, consider, tests below.
1) Try to connect to server from example/server directory with 'openssl s_client -connect 127.0.0.1:8085 -cipher "AES128-SHA"'. => Not OK.
2) Try to connect to testrfc7030.cisco.com with 'openssl s_client -connect testrfc7030.cisco.com:8443 -cipher "AES128-SHA"' => OK

So, my questions:
1) Which server is closer to RFC 7030? Is it not an issue that testrfc7030 accepts AES128-SHA which belongs to TLSv1.2 suite?
2) What is the difference between CA configurations in example server and testrfc7030?
3) Could you give me a hint how to modify example/server to accept AES128-SHA cipher as well?

Thank you in advance.

**Comment by jfigus** [comment]
Check the public key used in the example server.  It's probably using an ECDSA key.  The testrfc7030 server uses an RSA key.  The "AES128-SHA" cipher suite uses RSA.  Hence, you're telling the openssl client to only use this cipher suite, so it will only connect to a server using an RSA key.

It's been a while, going from memory here, but you should be able to modify example/server/ESTcommon.sh to use an RSA key.  Then re-run createCA.sh.  You would change the following two values to an empty string:

EST_OPENSSLCMD_EXTCANEWKEY_PARAM=" "
EST_OPENSSLCMD_CANEWKEY_PARAM=" "

**Comment by tysonite** [comment]
@jfigus, yeah, thanks. That's true. However, what configuration is correct or it does not matter?

**Comment by pritikin** [comment]
RFC7030 indicates that "TLS 1.1 [RFC4346 <https://tools.ietf.org/html/rfc4346>] (or a later version) MUST be used for all EST communications.”

General guidance is to use 1.2 (or 1.3 or 1.4 or whatever the latest and greatest is) but 1.1 was chosen for the RFC minimum in an attempt to accurately capture what we might expect implementors to have reasonable access to using their TLS libraries. 

- max

**Comment by jfigus** [comment]
AES128-SHA is certainly allowed, since this cipher suite is allowed by TLS 1.2.  Regarding whether you should use an RSA or ECDSA public key, that's up to you.  This is a deployment choice.  ECDSA allows much smaller keys with the same level of security.  I wouldn't use anything less than 2048 bit keys with RSA today.  For ECDSA, 256 bit keys should be sufficient.  OpenSSL has some fairly good performance optimizations for the NIST 256 bit ECDSA key (prime256v1).

**Comment by tysonite** [comment]
Thank you. More clear now.
