### ISSUE TITLE
Improve extra ex_data parameter of server callback functions

### ISSUE THREAD

**Issue by DDvO** [cisco/libest#5]
I came across the last parameter 'ex_data' of the server callback functions:

    int (*est_enroll_pkcs10_cb)(unsigned char *pkcs10, int p10_len, 
	                        unsigned char **pkcs7, int *cert_len,
				char *user_id, X509 *peer_cert,
				void *ex_data);
    int (*est_reenroll_pkcs10_cb)(unsigned char *pkcs10, int p10_len, 
	                          unsigned char **pkcs7, int *cert_len,
				  char *user_id, X509 *peer_cert,
				  void *ex_data);
    unsigned char *(*est_get_csr_cb)(int *csr_len, void *ex_data);
    int (*est_http_auth_cb)(struct est_ctx *ctx, EST_HTTP_AUTH_HDR *ah, 
	                    X509 *peer_cert, void *ex_data);

partially documented at the est_set_ex_data() function declaration in est.c .

I suggest completing its documentation in est_server.c and est_locl.h and removing its test use in estserver.c, as done tentatively in the diff I'm going to provide,

**Comment by jfigus** [comment]
Closing issue, still have not see a pull request with the proposed fix.

**Comment by DDvO** [comment]
The suggested improvements have been included, among many others, in the set of changes provided on March 20th.
