### ISSUE TITLE
Error make client example

### ISSUE THREAD

**Issue by darknesshadow** [cisco/libest#59]
Hi,
I'm trying to use this lib but when I try to compile the client example (with make) I have this issue : 
libtool:   error: cannot determine absolute directory name of '../../src/est/.libs'
Before that I have executed  "export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:/usr/local/est/lib"
(because the libcrypto.so is in the folder /x86_64-linux-gnu and libest.so is in /est/lib) and "export EST_OPENSSL_CACERT=../server/estCA/cacert.crt".
Thank's for your help

**Comment by rpb5bnc** [comment]
Hi,
    
    I'm not sure I follow exactly what is being attempted.  When the
    make is performed at the top level of the code base both the library
    is built and all example applications are built, including the
    estclient example application.  That is to say, when make is invoked
    at the top level, it will traverse all the directories looking for
    what needs to be built, and in addition to finding and building the
    library in src/est/, it will also traverse each of the directories
    in example/ and build all those applications as well.  
    
    So, when you state that you are trying to compile the client example
    (with make) and have this issue, are you saying you get this when
    you invoke make at the top level directory of the code base, or are
    you attempting to build just the example client application,
    estclient, down in the example/client/ directory?
    
    If it's the first case, then I have not seen this issue before.  I
    just pulled the code and went through the "./configure; make; make
    install" steps again and did not see it.  If you're attempting to do
    the second, I don't see why this is necessary since the
    example/client/estclient application should have already been built.
    
    Hope this helps. 
    
    On 3/9/18 10:09 AM, darknesshadow
      wrote:
    
    
      
      Hi,
        I'm trying to use this lib but when I try to compile the client
        example (with make) I have this issue :
        libtool: error: cannot determine absolute directory name of
        '../../src/est/.libs'
        Before that I have executed "export
        LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:/usr/local/est/lib"
        (because the libcrypto.so is in the folder /x86_64-linux-gnu and
        libest.so is in /est/lib) and "export
        EST_OPENSSL_CACERT=../server/estCA/cacert.crt".
        Thank's for your help
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      
        
          
          
          
          
        
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cisco/libest","title":"cisco/libest","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/cisco/libest"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Error make client example (#59)"}],"action":{"name":"View Issue","url":"https://github.com/cisco/libest/issues/59"}}}

**Comment by darknesshadow** [comment]
Oh I haven't seen that the client have been already compile... 
Really sorry for that ans thank you for losing your time with stupid question
