### ISSUE TITLE
Trouble building on Windows

### ISSUE THREAD

**Issue by takhtar786** [cisco/libest#63]
Hello,

I’m trying to build the library on Windows.  I’ve followed the instructions listed out at the README and was unable to get it working.  This is from a clean clone with no modifications.  I was able to get this built fine with no issues on Ubuntu16.

Steps I’ve done up to this point:
1.  Installed Gradle 2.12 (latest didn't work for me at all)	
2.  Built/installed OpenSSL and set SSL_DIR to the location specified by instructions
3.  Did NOT proceed with URIPARSER instructions.
4.  Downloaded Visual Studio 2013 and added location to the path (C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin).

Here is the output after running gradle estReleaseSharedLibrary task.  Any help or suggestions would be appreciated.

Thank you.

C:\Development\work\libest3>gradle estReleaseSharedLibrary
:compileEstReleaseSharedLibraryEstC
est.c
c:\development\work\libest3\src\est\est_client_proxy.h(53) : error C2061: syntax error : identifier 'SOCKET'
c:\development\work\libest3\src\est\est_client_proxy.h(54) : error C2059: syntax error : '}'
c:\development\work\libest3\src\est\est_client_proxy.h(56) : error C2143: syntax error : missing ')' before '*'
c:\development\work\libest3\src\est\est_client_proxy.h(56) : error C2143: syntax error : missing '{' before '*'
c:\development\work\libest3\src\est\est_client_proxy.h(56) : error C2371: 'tcw_opts_t' : redefinition; different basic types
        c:\development\work\libest3\src\est\est_client_proxy.h(46) : see declaration of 'tcw_opts_t'
c:\development\work\libest3\src\est\est_client_proxy.h(56) : error C2143: syntax error : missing ';' before '*'
c:\development\work\libest3\src\est\est_client_proxy.h(56) : error C2059: syntax error : 'type'
c:\development\work\libest3\src\est\est_client_proxy.h(57) : error C2059: syntax error : ')'
c:\development\work\libest3\src\est\est_client_proxy.h(58) : error C2143: syntax error : missing ')' before '*'
c:\development\work\libest3\src\est\est_client_proxy.h(58) : error C2143: syntax error : missing '{' before '*'
c:\development\work\libest3\src\est\est_client_proxy.h(58) : error C2059: syntax error : ')'
c:\development\work\libest3\src\est\est_locl.h(261) : error C2061: syntax error : identifier 'tcw_sock_t'
c:\development\work\libest3\src\est\est_locl.h(294) : error C2059: syntax error : '}'
C:\Development\work\libest3\src\est\est.c(590) : error C2037: left of 'est_mode' specifies undefined struct/union 'est_ctx'
C:\Development\work\libest3\src\est\est.c(612) : error C2037: left of 'ca_certs_len' specifies undefined struct/union 'est_ctx'
C:\Development\work\libest3\src\est\est.c(613) : error C2037: left of 'ca_certs_len' specifies undefined struct/union 'est_ctx'
C:\Development\work\libest3\src\est\est.c(620) : error C2037: left of 'ca_certs' specifies undefined struct/union 'est_ctx'
C:\Development\work\libest3\src\est\est.c(620) : error C2037: left of 'ca_certs_len' specifies undefined struct/union 'est_ctx'
C:\Development\work\libest3\src\est\est.c(620) : error C2198: 'malloc' : too few arguments for call
C:\Development\work\libest3\src\est\est.c(621) : error C2037: left of 'ca_certs' specifies undefined struct/union 'est_ctx'
C:\Development\work\libest3\src\est\est.c(627) : error C2037: left of 'ca_certs' specifies undefined struct/union 'est_ctx'
C:\Development\work\libest3\src\est\est.c(627) : error C2037: left of 'ca_certs_len' specifies undefined struct/union 'est_ctx'
C:\Development\work\libest3\src\est\est.c(627) : error C2198: 'memcpy_s' : too few arguments for call
C:\Development\work\libest3\src\est\est.c(651) : error C2037: left of 'trusted_certs_store' specifies undefined struct/union 'est_ctx'
C:\Development\work\libest3\src\est\est.c(652) : error C2037: left of 'trusted_certs_store' specifies undefined struct/union 'est_ctx'
C:\Development\work\libest3\src\est\est.c(656) : error C2037: left of 'trusted_certs_store' specifies undefined struct/union 'est_ctx'
C:\Development\work\libest3\src\est\est.c(656) : warning C4047: 'function' : 'X509_STORE *' differs in levels of indirection from 'int (__cdecl *)(int,X509_STORE_CTX *)'
C:\Development\work\libest3\src\est\est.c(656) : warning C4024: 'X509_STORE_set_verify_cb' : different types for formal and actual parameter 1
C:\Development\work\libest3\src\est\est.c(656) : error C2198: 'X509_STORE_set_verify_cb' : too few arguments for call
C:\Development\work\libest3\src\est\est.c(657) : error C2037: left of 'trusted_certs_store' specifies undefined struct/union 'est_ctx'
C:\Development\work\libest3\src\est\est.c(657) : warning C4133: 'function' : incompatible types - from 'unsigned char *' to 'X509_STORE *'
C:\Development\work\libest3\src\est\est.c(657) : warning C4047: 'function' : 'unsigned char *' differs in levels of indirection from 'int'
C:\Development\work\libest3\src\est\est.c(657) : warning C4024: 'ossl_init_cert_store' : different types for formal and actual parameter 2
C:\Development\work\libest3\src\est\est.c(657) : error C2198: 'ossl_init_cert_store' : too few arguments for call
C:\Development\work\libest3\src\est\est.c(691) : error C2037: left of 'ex_data' specifies undefined struct/union 'est_ctx'
C:\Development\work\libest3\src\est\est.c(694) : error C2037: left of 'ex_data' specifies undefined struct/union 'est_ctx'
C:\Development\work\libest3\src\est\est.c(715) : error C2037: left of 'ex_data' specifies undefined struct/union 'est_ctx'
C:\Development\work\libest3\src\est\est.c(715) : warning C4033: 'est_get_ex_data' must return a value
C:\Development\work\libest3\src\est\est.c(735) : error C2037: left of 'trusted_certs_store' specifies undefined struct/union 'est_ctx'
C:\Development\work\libest3\src\est\est.c(736) : error C2037: left of 'trusted_certs_store' specifies undefined struct/union 'est_ctx'
C:\Development\work\libest3\src\est\est.c(736) : error C2198: 'X509_STORE_free' : too few arguments for call
C:\Development\work\libest3\src\est\est.c(739) : error C2037: left of 'ca_certs' specifies undefined struct/union 'est_ctx'
C:\Development\work\libest3\src\est\est.c(740) : error C2037: left of 'ca_certs' specifies undefined struct/union 'est_ctx'
C:\Development\work\libest3\src\est\est.c(740) : error C2198: 'free' : too few arguments for call
C:\Development\work\libest3\src\est\est.c(743) : error C2037: left of 'retrieved_ca_certs' specifies undefined struct/union 'est_ctx'
C:\Development\work\libest3\src\est\est.c(744) : error C2037: left of 'retrieved_ca_certs' specifies undefined struct/union 'est_ctx'
C:\Development\work\libest3\src\est\est.c(744) : error C2198: 'free' : too few arguments for call
C:\Development\work\libest3\src\est\est.c(747) : error C2037: left of 'retrieved_csrattrs' specifies undefined struct/union 'est_ctx'
C:\Development\work\libest3\src\est\est.c(748) : error C2037: left of 'retrieved_csrattrs' specifies undefined struct/union 'est_ctx'
C:\Development\work\libest3\src\est\est.c(748) : error C2198: 'free' : too few arguments for call
C:\Development\work\libest3\src\est\est.c(751) : error C2037: left of 'server_csrattrs' specifies undefined struct/union 'est_ctx'
C:\Development\work\libest3\src\est\est.c(752) : error C2037: left of 'server_csrattrs' specifies undefined struct/union 'est_ctx'
C:\Development\work\libest3\src\est\est.c(752) : error C2198: 'free' : too few arguments for call
C:\Development\work\libest3\src\est\est.c(755) : error C2037: left of 'enrolled_client_cert' specifies undefined struct/union 'est_ctx'
C:\Development\work\libest3\src\est\est.c(756) : error C2037: left of 'enrolled_client_cert' specifies undefined struct/union 'est_ctx'
C:\Development\work\libest3\src\est\est.c(756) : error C2198: 'free' : too few arguments for call
C:\Development\work\libest3\src\est\est.c(759) : error C2037: left of 'ca_chain_raw' specifies undefined struct/union 'est_ctx'
C:\Development\work\libest3\src\est\est.c(760) : error C2037: left of 'ca_chain_raw' specifies undefined struct/union 'est_ctx'
C:\Development\work\libest3\src\est\est.c(760) : error C2198: 'free' : too few arguments for call
C:\Development\work\libest3\src\est\est.c(763) : error C2037: left of 'uri_path_segment' specifies undefined struct/union 'est_ctx'
C:\Development\work\libest3\src\est\est.c(764) : error C2037: left of 'uri_path_segment' specifies undefined struct/union 'est_ctx'
C:\Development\work\libest3\src\est\est.c(764) : error C2198: 'free' : too few arguments for call
C:\Development\work\libest3\src\est\est.c(767) : error C2037: left of 'dh_tmp' specifies undefined struct/union 'est_ctx'
C:\Development\work\libest3\src\est\est.c(768) : error C2037: left of 'dh_tmp' specifies undefined struct/union 'est_ctx'
C:\Development\work\libest3\src\est\est.c(768) : error C2198: 'DH_free' : too few arguments for call
C:\Development\work\libest3\src\est\est.c(774) : error C2037: left of 'ssl_ctx' specifies undefined struct/union 'est_ctx'
C:\Development\work\libest3\src\est\est.c(775) : error C2037: left of 'est_mode' specifies undefined struct/union 'est_ctx'
C:\Development\work\libest3\src\est\est.c(781) : error C2037: left of 'sess' specifies undefined struct/union 'est_ctx'
C:\Development\work\libest3\src\est\est.c(782) : error C2037: left of 'sess' specifies undefined struct/union 'est_ctx'
C:\Development\work\libest3\src\est\est.c(782) : error C2198: 'SSL_SESSION_free' : too few arguments for call
C:\Development\work\libest3\src\est\est.c(784) : error C2037: left of 'ssl_ctx' specifies undefined struct/union 'est_ctx'
C:\Development\work\libest3\src\est\est.c(784) : error C2198: 'SSL_CTX_free' : too few arguments for call
C:\Development\work\libest3\src\est\est.c(787) : error C2037: left of 'est_mode' specifies undefined struct/union 'est_ctx'
C:\Development\work\libest3\src\est\est.c(1089) : error C2037: left of 'enable_crl' specifies undefined struct/union 'est_ctx'
C:\Development\work\libest3\src\est\est.c(1131) : warning C4013: 'c2i_ASN1_OBJECT' undefined; assuming extern returning int
C:\Development\work\libest3\src\est\est.c(1131) : warning C4047: '=' : 'ASN1_OBJECT *' differs in levels of indirection from 'int'
C:\Development\work\libest3\src\est\est.c(1488) : warning C4047: '=' : 'ASN1_OBJECT *' differs in levels of indirection from 'int'
C:\Development\work\libest3\src\est\est.c(1815) : error C2037: left of 'uri_path_segment' specifies undefined struct/union 'est_ctx'
C:\Development\work\libest3\src\est\est.c(1816) : error C2037: left of 'uri_path_segment' specifies undefined struct/union 'est_ctx'
C:\Development\work\libest3\src\est\est.c(1816) : error C2198: 'free' : too few arguments for call
C:\Development\work\libest3\src\est\est.c(1817) : error C2037: left of 'uri_path_segment' specifies undefined struct/union 'est_ctx'
C:\Development\work\libest3\src\est\est.c(1820) : error C2037: left of 'uri_path_segment' specifies undefined struct/union 'est_ctx'
C:\Development\work\libest3\src\est\est.c(1821) : error C2037: left of 'uri_path_segment' specifies undefined struct/union 'est_ctx'
C:\Development\work\libest3\src\est\est.c(1825) : error C2037: left of 'uri_path_segment' specifies undefined struct/union 'est_ctx'
C:\Development\work\libest3\src\est\est.c(1825) : warning C4047: 'function' : 'char *' differs in levels of indirection from 'int'
C:\Development\work\libest3\src\est\est.c(1825) : warning C4024: 'strncpy_s' : different types for formal and actual parameter 1
C:\Development\work\libest3\src\est\est.c(1826) : warning C4047: 'function' : 'rsize_t' differs in levels of indirection from 'char *'
C:\Development\work\libest3\src\est\est.c(1826) : warning C4024: 'strncpy_s' : different types for formal and actual parameter 2
C:\Development\work\libest3\src\est\est.c(1826) : warning C4047: 'function' : 'const char *' differs in levels of indirection from 'int'
C:\Development\work\libest3\src\est\est.c(1826) : warning C4024: 'strncpy_s' : different types for formal and actual parameter 3
C:\Development\work\libest3\src\est\est.c(1826) : error C2198: 'strncpy_s' : too few arguments for call
C:\Development\work\libest3\src\est\est.c(1829) : error C2037: left of 'uri_path_segment' specifies undefined struct/union 'est_ctx'

est_client.c
C:\Development\work\libest3\src\est\est_client.c(101) : error C2079: 'mctx' uses undefined struct 'evp_md_ctx_st'
C:\Development\work\libest3\src\est\est_client.c(103) : warning C4133: 'function' : incompatible types - from 'int *' to 'EVP_MD_CTX *'
C:\Development\work\libest3\src\est\est_client.c(105) : warning C4133: 'function' : incompatible types - from 'int *' to 'EVP_MD_CTX *'
C:\Development\work\libest3\src\est\est_client.c(117) : error C2037: left of 'req_info' specifies undefined struct/union 'X509_req_st'
C:\Development\work\libest3\src\est\est_client.c(118) : warning C4133: 'function' : incompatible types - from 'int *' to 'EVP_MD_CTX *'
C:\Development\work\libest3\src\est\est_client.c(120) : warning C4013: 'EVP_MD_CTX_cleanup' undefined; assuming extern returning int
C:\Development\work\libest3\src\est\est_client.c(589) : error C2037: left of 'name' specifies undefined struct/union 'x509_st'
C:\Development\work\libest3\src\est\est_client.c(623) : error C2037: left of 'name' specifies undefined struct/union 'x509_st'
C:\Development\work\libest3\src\est\est_client.c(631) : error C2037: left of 'name' specifies undefined struct/union 'x509_st'
C:\Development\work\libest3\src\est\est_client.c(1613) : error C2037: left of 'signature' specifies undefined struct/union 'x509_st'
C:\Development\work\libest3\src\est\est_client.c(1621) : error C2037: left of 'signature' specifies undefined struct/union 'x509_st'
C:\Development\work\libest3\src\est\est_client.c(1717) : error C2037: left of 'req_info' specifies undefined struct/union 'X509_req_st'
C:\Development\work\libest3\src\est\est_client.c(3238) : error C2037: left of 'cert_info' specifies undefined struct/union 'x509_st'
C:\Development\work\libest3\src\est\est_client.c(3239) : error C2037: left of 'cert_info' specifies undefined struct/union 'x509_st'
C:\Development\work\libest3\src\est\est_client.c(3239) : error C2198: 'X509_REQ_add_extensions' : too few arguments for call
C:\Development\work\libest3\src\est\est_client.c(3663) : error C2037: left of 'objs' specifies undefined struct/union 'x509_store_st'
C:\Development\work\libest3\src\est\est_client.c(3663) : error C2198: 'sk_X509_OBJECT_num' : too few arguments for call

est_ossl_util.c
c:\development\work\libest3\src\est\est_client_proxy.h(53) : error C2061: syntax error : identifier 'SOCKET'
c:\development\work\libest3\src\est\est_client_proxy.h(54) : error C2059: syntax error : '}'
c:\development\work\libest3\src\est\est_client_proxy.h(56) : error C2143: syntax error : missing ')' before '*'
c:\development\work\libest3\src\est\est_client_proxy.h(56) : error C2143: syntax error : missing '{' before '*'
c:\development\work\libest3\src\est\est_client_proxy.h(56) : error C2371: 'tcw_opts_t' : redefinition; different basic types
        c:\development\work\libest3\src\est\est_client_proxy.h(46) : see declaration of 'tcw_opts_t'
c:\development\work\libest3\src\est\est_client_proxy.h(56) : error C2143: syntax error : missing ';' before '*'
c:\development\work\libest3\src\est\est_client_proxy.h(56) : error C2059: syntax error : 'type'
c:\development\work\libest3\src\est\est_client_proxy.h(57) : error C2059: syntax error : ')'
c:\development\work\libest3\src\est\est_client_proxy.h(58) : error C2143: syntax error : missing ')' before '*'
c:\development\work\libest3\src\est\est_client_proxy.h(58) : error C2143: syntax error : missing '{' before '*'
c:\development\work\libest3\src\est\est_client_proxy.h(58) : error C2059: syntax error : ')'
c:\development\work\libest3\src\est\est_locl.h(261) : error C2061: syntax error : identifier 'tcw_sock_t'
c:\development\work\libest3\src\est\est_locl.h(294) : error C2059: syntax error : '}'
C:\Development\work\libest3\src\est\est_ossl_util.c(182) : error C2037: left of 'name' specifies undefined struct/union 'x509_st'

est_server.c
C:\Development\work\libest3\src\est\est_server.c(569) : error C2037: left of 'single' specifies undefined struct/union 'x509_attributes_st'
C:\Development\work\libest3\src\est\est_server.c(570) : error C2037: left of 'value' specifies undefined struct/union 'x509_attributes_st'
C:\Development\work\libest3\src\est\est_server.c(574) : error C2037: left of 'value' specifies undefined struct/union 'x509_attributes_st'
C:\Development\work\libest3\src\est\est_server.c(574) : warning C4047: 'function' : 'const stack_st_ASN1_TYPE *' differs in levels of indirection from 'int'
C:\Development\work\libest3\src\est\est_server.c(574) : warning C4024: 'sk_ASN1_TYPE_value' : different types for formal and actual parameter 1
C:\Development\work\libest3\src\est\est_server.c(574) : error C2198: 'sk_ASN1_TYPE_value' : too few arguments for call
C:\Development\work\libest3\src\est\est_server.c(973) : warning C4013: 'c2i_ASN1_OBJECT' undefined; assuming extern returning int
C:\Development\work\libest3\src\est\est_server.c(973) : warning C4047: '=' : 'ASN1_OBJECT *' differs in levels of indirection from 'int'

:compileEstReleaseSharedLibraryEstC FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileEstReleaseSharedLibraryEstC'.
> Multiple build operations failed.
      C compiler failed while compiling est.c.
      C compiler failed while compiling est_client.c.
      C compiler failed while compiling est_ossl_util.c.
      C compiler failed while compiling est_server.c.
  See the complete log at: file:///C:/Development/work/libest3/build/tmp/compileEstReleaseSharedLibraryEstC/output.txt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 10.452 secs

C:\Development\work\libest3>

**Comment by rpb5bnc** [comment]
This does not look familiar to me.  Although recent efforts on libEST have focused on Linux environments this release of the library was building and running on Windows, at least, based on the last automated regression tests that had been made against this release.

One clue I see is,

est_client.c
C:\Development\work\libest3\src\est\est_client.c(101) : error C2079: 'mctx' uses undefined struct 'evp_md_ctx_st'

This indicates to me that possibly an OpenSSL 1.1.x version was used when attempting to build libEST instead of an OpenSSL 1.0.2 version.  This structure is one of the many structures that have become opaque starting with OpenSSL 1.1.0.  At this time libEST is supported with OpenSSL 1.0.2 and not 1.1.0.

So as a starting point I would ensure that OpenSSL 1.0.2p is being used.  This may not address the first error with est.c

est.c
c:\development\work\libest3\src\est\est_client_proxy.h(53) : error C2061: syntax error : identifier 'SOCKET'

This looks to me like include search paths may not be set up correctly.  'SOCKET' I believe is defined in winsock.h or maybe winsock2.h over in Windows.

**Comment by takhtar786** [comment]
Using OpenSSL 1.0.2p did the trick!  Thank you.
