### ISSUE TITLE
Question: Which certificate chain the “/cacerts” operation is supposed to return?

### ISSUE THREAD

**Issue by achuchev** [cisco/libest#69]
I have a case where the TLS certificate used on the EST server for HTTPS is issued by publicly trusted CA (Let’s Encrypt), but the EST CA which is used to issue client certificates (requested via /simpleenroll) is internal (AD CS).

Reading “2.1.  Obtaining CA Certificates” section of RFC 7030 you can see: 

> 2.1.  Obtaining CA Certificates
> The EST client can request a copy of the current EST CA
> certificate(s) from the EST server.  The EST client is assumed to
> perform this operation before performing other operations.
> Throughout this document we assume the EST CA has a certificate that
> is used by the client to verify signed objects issued by the CA,
> e.g., certificates and certificate revocation lists (CRLs), and that
> a different certificate than the one used to verify signatures on
> certificates and CRLs is used when EST protocol communication
> requires additional encryption.

This makes me think that the /cacerts must return the certificate chain of the internal CA (AD CS), because the EST client will use it to verify the signed objects (cert/crl).

However, reading the following “4.1.1. Bootstrap Distribution of CA Certificates” and “4.1.3. CA Certificates Response”

> 4.1.1.  Bootstrap Distribution of CA Certificates
> ...
> The EST client uses the /cacerts response to establish an Explicit
> Trust Anchor database for subsequent TLS authentication of the EST
> server.  EST clients MUST NOT engage in any other protocol exchange
> until after the /cacerts response has been accepted and a new TLS
> session has been established (using TLS certificate-based
> authentication).
> 
> 4.1.3. CA Certificates Response
> ...
> The EST server MUST include the current root CA certificate in the
> response.  The EST server MUST include any additional certificates
> the client would need to build a chain from an EST CA-issued
> certificate to the current EST CA TA.  For example, if the EST CA is
> a subordinate CA, then all the appropriate subordinate CA
> certificates necessary to build a chain to the root EST CA are
> included in the response.
> ...

Here the RFC is talking about the TLS certificate used for server authentication. In my case this is the publicly trusted CA (Let’s Encrypt).

So, which certificate chain the “/cacerts” operation is supposed to return?

**Comment by rpb5bnc** [comment]
Hi,
    
    The payload returned in response to a /cacerts should include the CA
    certificates for the local PKI domain.  In this RFC this is referred
    to as the explicit trust anchor database.  The idea is that the
    client devices would be preloaded with trust anchor certificates
    that would allow the client to verify the TLS server certificate
    that the client receives on the first TLS connection to the EST
    server.  In this RFC this preloaded trust anchor chain of
    certificates is referred to as an implicit trust anchor database. 
    It is this first connection by the EST client where it issues the
    /cacerts and would obtain the explicit trust anchor database.  
    
    The explicit trust anchor database may contain multiple trust anchor
    chains, so it can include both the CA trust chain for the local PKI
    domain as well as the CA trust chain needed for the initial
    connection.  Once the EST client obtains the explicit trust anchor
    database on the /cacerts it must use only this database of CA trust
    chains going forward.
    
    Hope this helps,
    Pete
    
    On 3/19/19 2:16 PM, achuchev wrote:
    
    
      
      I have a case where the TLS certificate used on the EST server
        for HTTPS is issued by publicly trusted CA (Let’s Encrypt), but
        the EST CA which is used to issue client certificates (requested
        via /simpleenroll) is internal (AD CS).
      Reading “2.1. Obtaining CA Certificates” section of RFC 7030
        you can see:
      
        2.1. Obtaining CA Certificates
          The EST client can request a copy of the current EST CA
          certificate(s) from the EST server. The EST client is assumed
          to
          perform this operation before performing other operations.
          Throughout this document we assume the EST CA has a
          certificate that
          is used by the client to verify signed objects issued by the
          CA,
          e.g., certificates and certificate revocation lists (CRLs),
          and that
          a different certificate than the one used to verify signatures
          on
          certificates and CRLs is used when EST protocol communication
          requires additional encryption.
      
      This makes me think that the /cacerts must return the
        certificate chain of the internal CA (AD CS), because the EST
        client will use it to verify the signed objects (cert/crl).
      However, reading the following “4.1.1. Bootstrap Distribution
        of CA Certificates” and “4.1.3. CA Certificates Response”
      
        4.1.1. Bootstrap Distribution of CA Certificates
          ...
          The EST client uses the /cacerts response to establish an
          Explicit
          Trust Anchor database for subsequent TLS authentication of the
          EST
          server. EST clients MUST NOT engage in any other protocol
          exchange
          until after the /cacerts response has been accepted and a new
          TLS
          session has been established (using TLS certificate-based
          authentication).
        4.1.3. CA Certificates Response
          ...
          The EST server MUST include the current root CA certificate in
          the
          response. The EST server MUST include any additional
          certificates
          the client would need to build a chain from an EST CA-issued
          certificate to the current EST CA TA. For example, if the EST
          CA is
          a subordinate CA, then all the appropriate subordinate CA
          certificates necessary to build a chain to the root EST CA are
          included in the response.
          ...
      
      Here the RFC is talking about the TLS certificate used for
        server authentication. In my case this is the publicly trusted
        CA (Let’s Encrypt).
      So, which certificate chain the “/cacerts” operation is
        supposed to return?
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cisco/libest","title":"cisco/libest","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/cisco/libest"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Which certificate chain the “/cacerts” operation is supposed to return? (#69)"}],"action":{"name":"View Issue","url":"https://github.com/cisco/libest/issues/69"}}}
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/cisco/libest/issues/69",
"url": "https://github.com/cisco/libest/issues/69",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by achuchev** [comment]
@rpb5bnc This makes sense. Thanks for the detailed explanation.
