### ISSUE TITLE
any plan for openssl 1.1.0 support

### ISSUE THREAD

**Issue by testup** [cisco/libest#71]
any plan for openssl 1.1.0 support??

**Comment by rpb5bnc** [comment]
Hi, yes, working on it.  Work has been really demanding lately.  It's all working internally.  Problem with just pushing it the external github is that the 1.1.x support went in along with some other features, causing the 1.1.x support to need to be manually ported over to the outside version of libest.

Support for OpenSSL 1.1.0 ends on 9/11/19, so the changes will technically allows libest to run work with OpenSSL 1.1.1.

Regards.

On 6/25/19 6:28 AM, testup wrote:

any plan for openssl 1.1.0 support??
