### ISSUE TITLE
Unable to compile on RHEL 7

### ISSUE THREAD

**Issue by SarwateShubham** [cisco/libest#76]
est.h:27:25: fatal error: openssl/srp.h: No such file or directory

$ openssl version
OpenSSL 1.0.2d 9 Jul 2015

Seeing error compiling for RHEL 7.

**Comment by rpb5bnc** [comment]
This is not something I've seen before.  The include for srp.h in est.h is not the first file to be included from the OpenSSL installation.  All I can say about this one is that it appears that the installation of OpenSSL appears to not be correct.  If the compiler was able to find

#include <openssl/ssl.h>
#include <openssl/engine.h>
#include <openssl/conf.h>

it should have been able to find

#include <openssl/srp.h>

I would look to make sure that the OpenSSL installation that was stated with --with-ssl-dir= when configure was run is really what is now being pointed to and is available to be used during the running of make.

I believe that support for SRP was in OpenSSL at least as far back as OpenSSL 1.0.1, and libest definitely builds against all releases of OpenSSL 1.0.2.

Pete

On 1/14/20 8:27 PM, Shubham Sarwate wrote:

est.h:27:25: fatal error: openssl/srp.h: No such file or directory

$ openssl version
OpenSSL 1.0.2d 9 Jul 2015

Seeing error compiling for RHEL 7.

**Comment by SarwateShubham** [comment]
Thanks for the suggesiton Pete!
--with-ssl-dir= had to be corrected to point to the correct place of openssl installation.
