### ISSUE TITLE
Make failed when building the latest libest

### ISSUE THREAD

**Issue by vochong** [cisco/libest#94]
Hi,
I tried to build libest on an ArchLinux machine:

./configure --disable-safec && make && sudo make install

I got these error when running "make".   Could you please help me remedy this problem. Thanks.

/bin/sh ../../libtool  --tag=CC   --mode=link gcc -I/usr/local/ssl/include -I../.. -I/tmp/libest/safe_c_stub/include  -g -O2 -Wall -I/usr/local/ssl/include -release 3.2.0p  -L/usr/local/ssl/lib -L/tmp/libest/safe_c_stub/lib -o libest.la -rpath /usr/local/est/lib est.lo est_client.lo est_server.lo est_server_http.lo est_proxy.lo est_client_http.lo est_ossl_util.lo est_client_proxy.lo jsmn.lo multipart_parser.lo est_enhcd_cert_auth.lo est_server_coap.lo /tmp/libest/safe_c_stub/lib -lcrypto -lssl -lcrypto -lpthread -ldl  -lsafe_lib
libtool: link: gcc -shared  -fPIC -DPIC  .libs/est.o .libs/est_client.o .libs/est_server.o .libs/est_server_http.o .libs/est_proxy.o .libs/est_client_http.o .libs/est_ossl_util.o .libs/est_client_proxy.o .libs/jsmn.o .libs/multipart_parser.o .libs/est_enhcd_cert_auth.o .libs/est_server_coap.o   -L/usr/local/ssl/lib -L/tmp/libest/safe_c_stub/lib -lssl -lcrypto -lpthread -ldl -lsafe_lib  -g -O2   -Wl,-soname -Wl,libest-3.2.0p.so -o .libs/libest-3.2.0p.so
/usr/bin/ld: .libs/est_client.o:/tmp/libest/src/est/est_locl.h:593: multiple definition of `e_ctx_ssl_exdata_index'; .libs/est.o:/tmp/libest/src/est/est_locl.h:593: first defined here
/usr/bin/ld: .libs/est_server.o:/tmp/libest/src/est/est_locl.h:593: multiple definition of `e_ctx_ssl_exdata_index'; .libs/est.o:/tmp/libest/src/est/est_locl.h:593: first defined here
/usr/bin/ld: .libs/est_server_http.o:/tmp/libest/src/est/est_locl.h:593: multiple definition of `e_ctx_ssl_exdata_index'; .libs/est.o:/tmp/libest/src/est/est_locl.h:593: first defined here
/usr/bin/ld: .libs/est_proxy.o:/tmp/libest/src/est/est_locl.h:593: multiple definition of `e_ctx_ssl_exdata_index'; .libs/est.o:/tmp/libest/src/est/est_locl.h:593: first defined here
/usr/bin/ld: .libs/est_client_http.o:/tmp/libest/src/est/est_locl.h:593: multiple definition of `e_ctx_ssl_exdata_index'; .libs/est.o:/tmp/libest/src/est/est_locl.h:593: first defined here
/usr/bin/ld: .libs/est_ossl_util.o:/tmp/libest/src/est/est_locl.h:593: multiple definition of `e_ctx_ssl_exdata_index'; .libs/est.o:/tmp/libest/src/est/est_locl.h:593: first defined here
/usr/bin/ld: .libs/est_client_proxy.o:/tmp/libest/src/est/est_locl.h:593: multiple definition of `e_ctx_ssl_exdata_index'; .libs/est.o:/tmp/libest/src/est/est_locl.h:593: first defined here
/usr/bin/ld: .libs/est_enhcd_cert_auth.o:/tmp/libest/src/est/est_locl.h:593: multiple definition of `e_ctx_ssl_exdata_index'; .libs/est.o:/tmp/libest/src/est/est_locl.h:593: first defined here
/usr/bin/ld: .libs/est_server_coap.o:/tmp/libest/src/est/est_locl.h:593: multiple definition of `e_ctx_ssl_exdata_index'; .libs/est.o:/tmp/libest/src/est/est_locl.h:593: first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:460: libest.la] Error 1
make[2]: Leaving directory '/tmp/libest/src/est'
make[1]: *** [Makefile:359: all-recursive] Error 1
make[1]: Leaving directory '/tmp/libest/src'
make: *** [Makefile:403: all-recursive] Error 1

**Comment by rpb5bnc** [comment]
Hello,

Appears it's a superfluous declaration that's never been cleaned up.  Been in the code since day 1.  I believe you can either add an "extern" in front of the declaration in est_lcl.h or just delete it entirely. 

We primarily use Ubuntu and CentOS as our distros for Linux based development and testing of EST, currently 18.04 and 7.x respectively.  I'm guessing the tool chain used in the version of ArchLinux you are using may be newer than what we use and this newer version is now a bit more lintier by default and finally called out the conflict.

I believe it's fine to just remove the line in est_lcl.h

Pete

**Comment by vochong** [comment]
Thanks a lot Pete.  I followed your instruction and was able to build it successfully.

Best regards,
Eric

**Comment by brokoler** [comment]
Hello,

I'm having exactly the same issue with the latest release in version 3.2.0, but I can't find a file or a line called "est_lcl.h" to fix the issue by myself.

Was anything changed since then and is it needed to adjust a different parameter instead?

**Comment by frasertweedale** [comment]
The file to modify is `src/est/est_locl.h`.
