### ISSUE TITLE
rename main branch to main 

### ISSUE THREAD

**Issue by fluffy** [cisco/libest#98]

**Comment by csosto-pk** [comment]
Hi @fluffy , 
Do you mean to rename the "master" branch to "main"? Why?

**Comment by tomaszpr** [comment]
because of this:
https://nypost.com/2020/07/25/these-are-the-innocuous-words-progressives-want-to-ban/

It's crazy! :) :) :)
Please don't do this. And don't forget to change name of your HDD from master to something else.

**Comment by fluffy** [comment]
@tomaszpr - I know like it might no seem like it matters how words like this are used, but to some people it does. And I don't think it costs us anything to use a different word. Cisco is very much trying to make an inclusive future for all on the internet, and will this help, maybe, so we want to do that.
